[project]
name = "nophish-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.18.0",
    "arq>=0.26.3",
    "dotenv>=0.9.9",
    "fastapi>=0.127.0",
    "fastapi-pagination>=0.15.4",
    "fake-useragent>=2.2.0",
    "firebase-admin>=7.1.0",
    "httpx>=0.28.1",
    "idna>=3.11",
    "openai>=2.14.0",
    "playwright>=1.56.0",
    "pgvector>=0.3.0",
    "psycopg[binary]>=3.2.0",
    "pydantic>=2.12.5",
    "redis>=5.3.1",
    "sentence-transformers>=3.0.0",
    "sqlmodel>=0.0.29",
    "uvicorn>=0.40.0",
]
