"""added packgename to notifications

Revision ID: 18da0b1782d3
Revises: d9f0c9642887
Create Date: 2025-07-16 19:52:15.088184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '18da0b1782d3'
down_revision: Union[str, None] = 'd9f0c9642887'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('packageName', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'packageName')
    # ### end Alembic commands ###
