"""added rel hash

Revision ID: 3397e178827d
Revises: 645dcf5a8f12
Create Date: 2025-12-27 17:29:37.682036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3397e178827d'
down_revision: Union[str, None] = '645dcf5a8f12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('releventinfo', sa.Column('hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('releventinfo', 'hash')
    # ### end Alembic commands ###
