"""added rel info

Revision ID: 645dcf5a8f12
Revises: ec730ee26b71
Create Date: 2025-12-27 17:08:05.306211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '645dcf5a8f12'
down_revision: Union[str, None] = 'ec730ee26b71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('releventinfo',
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('packageName', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('urls', sa.JSON(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('releventinfo')
    # ### end Alembic commands ###
