"""added extraTitle and isGroup

Revision ID: ec730ee26b71
Revises: 18da0b1782d3
Create Date: 2025-12-27 11:44:41.065388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ec730ee26b71'
down_revision: Union[str, None] = '18da0b1782d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('extraTitle', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('notification', sa.Column('isGroup', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'isGroup')
    op.drop_column('notification', 'extraTitle')
    # ### end Alembic commands ###
